spring.application.name=haugiang
spring.datasource.url=${DBMS_CONNECTION:jdbc:mysql://localhost:3306/sale_clothes}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:haubnvn2004}

jwt.signerKey="arMODgCofeYgbKiuwxlx4jLAd5FJ2GGND+CnK0x+eSombLbtSbFdrFCOFK1xkLZe"
jwt.valid-duration=2
jwt.refresh-duration=24

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

#spring.web.resources.static-locations=file:/app/images/
spring.web.resources.static-locations=file:/F:/WorkSpace/Project/saleClothes/Image/
app.file.upload-dir=F:/WorkSpace/Project/saleClothes/Image/

server.image.url=http://localhost:8081/images/

server.port=8081

#config redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#Kafka server url
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#0: no wait for kafka response
#1: leader write success, not wait for follower
#-1: wait for all leader and replication
spring.kafka.producer.acks=-1
spring.kafka.producer.retries=1

#prevent duplicate send
spring.kafka.producer.properties.[enable.idempotence]=true
spring.kafka.producer.properties.[max.in.flight.requests.per.connection]=5